default: &default
  adapter: postgresql
  encoding: unicode
  database: gls_db_development
  pool: 5
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: social_app_development

test:
  <<: *default
  database: social_app_test

production:
  <<: *default
  database: social_app_production